### ISSUE TITLE
Wrong locale for the chart

### ISSUE THREAD

**Issue by lofidewanto** [interseroh/report-cockpit-birt-web#19]
Although I used German for the locale I get the months in English. Here is a comparison between the old birt-viewer and our new one (see screenshots).

Our Birt viewer:
![error-date-birt-chart-new](https://cloud.githubusercontent.com/assets/1212950/9518880/aeb9009a-4cba-11e5-9ed4-edf9fdf6d067.png)
Old Birt viewer:
![error-date-birt-chart-old](https://cloud.githubusercontent.com/assets/1212950/9518960/42f92960-4cbb-11e5-98ba-19bb3d2391c8.png)

**Comment by idueppe** [comment]
Lofi, could you provide an example report to write my tests against it?

**Comment by idueppe** [comment]
I cannot reproduce the bug. I added a demo report `chartdate` to the project. According to the selected language a localized date is printing within the chart and table. Please see below. 

<img width="1059" alt="birt_report_cockpit" src="https://cloud.githubusercontent.com/assets/1124763/9699153/36633d0c-53d8-11e5-844f-06d2c1dda90a.png">

<img width="1015" alt="birt_report_cockpit" src="https://cloud.githubusercontent.com/assets/1124763/9699159/5281294a-53d8-11e5-935c-59313231b329.png">

**Comment by lofidewanto** [comment]
I still see the same problem in my report. Additionally I also see the wrong locale in Excel and PDF.

@idueppe: could we see this error live? Thanks!

**Comment by idueppe** [comment]
What do you see in the Test-Report?

**Comment by idueppe** [comment]
Please make a try and add the monat_web_desc column to the table blow the chart. I still belief that the database is returning different data because I could not belief that the runtime engine is translating the string values of the data set.

And second please change the data column of the chart to a column of type date instead of varchar2.

**Comment by idueppe** [comment]
Guess it is fixed now. Have a look at the screenshots.
![birt_report_cockpit](https://cloud.githubusercontent.com/assets/1124763/14157611/03a6dbfc-f6cc-11e5-872e-4cab14e4468e.png)

![birt_report_cockpit2](https://cloud.githubusercontent.com/assets/1124763/14157617/0b00f158-f6cc-11e5-8aaa-61ca082c7a8d.png)

**Comment by lofidewanto** [comment]
I still see the wrong locale for the chart... see attached pic.

![error-month-english](https://cloud.githubusercontent.com/assets/1212950/14253667/b5cdf216-fa8c-11e5-9335-efa75df93ed9.jpg)

**Comment by idueppe** [comment]
It seems like a bug in BIRT. It seems that it uses the jvm default ULocale for charts instead of the render options locale. As you can see in the screenshot below by setting the request parameter `__locale=en` the date format changed in the upper right corner but the month with the charts are still in german.

![birt_report_viewer_bug](https://cloud.githubusercontent.com/assets/1124763/14350289/d2002628-fcc8-11e5-82b0-36efb3fb88ed.png)

**Comment by idueppe** [comment]
The problem is that the underlying database table uses the current jdbc connection locale to generate the data on the fly.
```sql 
...
"MONAT_WEB_DESC" VARCHAR2(75 CHAR) GENERATED ALWAYS AS (TO_CHAR("WEBSERVICE_DATUM",'MON YYYY')) VIRTUAL VISIBLE,
...
```

You could reproduce it with a small test:
```java
JdbcTemplate jdbc = new JdbcTemplate(dataSource);

Locale.setDefault(Locale.JAPAN);
System.out.println("JAPAN:" + jdbc.queryForObject("select MONAT_WEB_DESC FROM BTEVWE_VW_ENT_REP WHERE ROWID='AAAsaWAAFAAAM9zAAJ'", String.class));

Locale.setDefault(Locale.ENGLISH);
System.out.println("ENGLISH:" + jdbc.queryForObject("select MONAT_WEB_DESC FROM BTEVWE_VW_ENT_REP WHERE ROWID='AAAsaWAAFAAAM9zAAJ'", String.class));

Locale.setDefault(Locale.GERMAN);
System.out.println("GERMAN:" + jdbc.queryForObject("select MONAT_WEB_DESC FROM BTEVWE_VW_ENT_REP WHERE ROWID='AAAsaWAAFAAAM9zAAJ'", String.class));
```
Adjusting the locale of the jdbc connection is not covered by BIRT.

**Comment by lofidewanto** [comment]
Setting the locale in Java:

`Locale.setDefault(Locale.GERMAN)`

or from outside:
`
java -Duser.country=DE -Duser.language=de`
